const authorValues = [
  {
    author_no: 1,
    author_name: "Quinton Hannon",
    university: "Stanford University",
    date_of_birth: "1966-10-21",
    h_index: 20,
    gender: "m",
    mentor: 1,
  },
  {
    author_no: 2,
    author_name: "Robbie Hanzlik",
    university: "University of Oxford",
    date_of_birth: "1961-11-06",
    h_index: 15,
    gender: "m",
    mentor: 2,
  },
  {
    author_no: 3,
    author_name: "Ed Etheridge",
    university: "Utrecht University",
    date_of_birth: "1981-01-02",
    h_index: 25,
    gender: "m",
    mentor: 3,
  },
  {
    author_no: 4,
    author_name: "Daren Suriel",
    university: "Stanford University",
    date_of_birth: "1914-08-04",
    h_index: 41,
    gender: "m",
    mentor: 4,
  },
  {
    author_no: 5,
    author_name: "Homer Vangundy",
    university: "University of Chicago",
    date_of_birth: "1924-01-21",
    h_index: 20,
    gender: "m",
    mentor: 5,
  },
  {
    author_no: 6,
    author_name: "Federico Amico",
    university: "University of Chicago",
    date_of_birth: "1997-01-15",
    h_index: 10,
    gender: "m",
    mentor: 6,
  },
  {
    author_no: 7,
    author_name: "Xavier Murrah",
    university: "Princeton University",
    date_of_birth: "1920-04-08",
    h_index: 55,
    gender: "m",
    mentor: 7,
  },
  {
    author_no: 8,
    author_name: "Perry Schlegel",
    university: "Stanford University",
    date_of_birth: "1926-12-17",
    h_index: 60,
    gender: "m",
    mentor: 8,
  },
  {
    author_no: 9,
    author_name: "Rosaria Tank",
    university: "Stanford University",
    date_of_birth: "1918-02-07",
    h_index: 8,
    gender: "f",
    mentor: 9,
  },
  {
    author_no: 10,
    author_name: "Karolyn Marotta",
    university: "University of Chicago",
    date_of_birth: "1979-02-23",
    h_index: 7,
    gender: "f",
    mentor: 10,
  },
  {
    author_no: 11,
    author_name: "Marcelina Calvo",
    university: "University of Chicago",
    date_of_birth: "1979-04-19",
    h_index: 6,
    gender: "f",
    mentor: 11,
  },
  {
    author_no: 12,
    author_name: "Tran Sester",
    university: "Stanford University",
    date_of_birth: "1960-05-24",
    h_index: 17,
    gender: "f",
    mentor: 12,
  },
  {
    author_no: 13,
    author_name: "Perla Snipes",
    university: "Princeton University",
    date_of_birth: "1963-08-23",
    h_index: 15,
    gender: "f",
    mentor: 13,
  },
  {
    author_no: 14,
    author_name: "Letitia Liddle",
    university: "Stanford University",
    date_of_birth: "1965-02-09",
    h_index: 14,
    gender: "f",
    mentor: 14,
  },
  {
    author_no: 15,
    author_name: "Neomi Palomo",
    university: "Yale University",
    date_of_birth: "1976-10-27",
    h_index: 4,
    gender: "f",
    mentor: 15,
  },
];

const researchPaperValues = [
  {
    paper_id: 1,
    paper_title: "Should social be forbidden in all its forms?",
    conference: "society Conference",
    publish_date: "2017-09-11",
  },
  {
    paper_id: 2,
    paper_title: "Should social be allowed in the workplace?",
    conference: "society Conference",
    publish_date: "2010-02-05",
  },
  {
    paper_id: 3,
    paper_title:
      "Is economic too dependent on internet and technology development?",
    conference: "society Conference",
    publish_date: "2012-02-05",
  },
  {
    paper_id: 4,
    paper_title: "Does economic create isolation?",
    conference: "society Conference",
    publish_date: "2020-12-05",
  },
  {
    paper_id: 5,
    paper_title: "Should economic encourage entrepreneurship development?",
    conference: "society Conference",
    publish_date: "2002-05-05",
  },
  {
    paper_id: 6,
    paper_title: "Should economic be free for all residents of a city?",
    conference: "society Conference",
    publish_date: "2005-12-05",
  },
  {
    paper_id: 7,
    paper_title: "Is economic a key issue for the earth?",
    conference: "society Conference",
    publish_date: "2008-02-05",
  },
  {
    paper_id: 8,
    paper_title: "Should social be forbidden in all its forms?",
    conference: "society Conference",
    publish_date: "2018-06-05",
  },
  {
    paper_id: 9,
    paper_title: "Does social create isolation?",
    conference: "society Conference",
    publish_date: "2018-02-05",
  },
  {
    paper_id: 10,
    paper_title: "Should environment be free for all residents of a city?",
    conference: "environment Conference",
    publish_date: "2011-02-05",
  },
  {
    paper_id: 11,
    paper_title: "Should environment encourage entrepreneurship development?",
    conference: "environment Conference",
    publish_date: "2011-02-05",
  },
  {
    paper_id: 12,
    paper_title: "Should environment be private?",
    conference: "environment Conference",
    publish_date: "2004-02-05",
  },
  {
    paper_id: 13,
    paper_title: "Is environment an invasion of person privacy?",
    conference: "environment Conference",
    publish_date: "2003-02-05",
  },
  {
    paper_id: 14,
    paper_title: "Should political be allowed in the workplace?",
    conference: "political Conference",
    publish_date: "2015-02-05",
  },
  {
    paper_id: 15,
    paper_title: "Should environment be forbidden in all its forms?",
    conference: "environment Conference",
    publish_date: "2021-02-05",
  },
  {
    paper_id: 1,
    paper_title: "Is political a key issue for the earth?",
    conference: "political Conference",
    publish_date: "1999-02-05",
  },
  {
    paper_id: 2,
    paper_title: "Should political be illegal?",
    conference: "political Conference",
    publish_date: "1999-04-05",
  },
  {
    paper_id: 3,
    paper_title: "Should political encourage entrepreneurship development?",
    conference: "political Conference",
    publish_date: "1995-02-05",
  },
  {
    paper_id: 4,
    paper_title: "Should social be illegal?",
    conference: "political Conference",
    publish_date: "2000-02-05",
  },
  {
    paper_id: 5,
    paper_title: "Should political be free for all residents of a city?",
    conference: "political Conference",
    publish_date: "2000-11-05",
  },
  {
    paper_id: 6,
    paper_title: "Should heritage be illegal?",
    conference: "heritage Conference",
    publish_date: "2015-11-05",
  },
  {
    paper_id: 7,
    paper_title: "Should heritage be free for all residents of a city?",
    conference: "heritage Conference",
    publish_date: "1998-10-05",
  },
  {
    paper_id: 8,
    paper_title: "Should heritage encourage entrepreneurship development?",
    conference: "heritage Conference",
    publish_date: "2002-10-05",
  },
  {
    paper_id: 9,
    paper_title:
      "Is heritage too dependent on internet and technology development?",
    conference: "heritage Conference",
    publish_date: "2013-10-05",
  },
  {
    paper_id: 10,
    paper_title: "Is heritage a key issue for the earth?",
    conference: "heritage Conference",
    publish_date: "2013-09-05",
  },
  {
    paper_id: 11,
    paper_title: "Evolution of history",
    conference: "history Conference",
    publish_date: "2015-09-05",
  },
  {
    paper_id: 12,
    paper_title: "Advances of history",
    conference: "history Conference",
    publish_date: "2017-08-05",
  },
  {
    paper_id: 13,
    paper_title: "Why history is important",
    conference: "history Conference",
    publish_date: "2006-07-05",
  },
  {
    paper_id: 14,
    paper_title: "The value of history in life",
    conference: "history Conference",
    publish_date: "2009-06-05",
  },
  {
    paper_id: 15,
    paper_title: "Using the history",
    conference: "history Conference",
    publish_date: "2010-05-05",
  },
];

module.exports = { authorValues, researchPaperValues };
